name: bookstore_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  http: ^1.2.1
  google_fonts: ^6.1.0
  flex_color_scheme: ^7.3.1
  vector_math: ^2.1.4
  flutter_staggered_grid_view: ^0.7.0
  provider: ^6.1.1
  sqflite: ^2.3.2
  url_launcher: ^6.2.5
  html: ^0.15.4
  transparent_image: ^2.0.1
  page_transition: ^2.1.0
  connectivity_watcher: ^1.0.3
  curved_navigation_bar: ^1.0.2
  fl_chart: ^0.66.2
  flutter_svg: ^2.0.5
 


  share: any
  connectivity: any
  path: any

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

